spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecom
    username: root
    password: root1234
  boot:
    admin:
      client:
        url: http://localhost:1111/
        
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: '*'    
  
      
